/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Color;
import javax.swing.BorderFactory;
import utility.BDUtility;

/**
 *
 * @author PAWAN
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
       BDUtility.setImage(this, "/utility/images/abc1.jpg", 1366, 768);
       this.getRootPane().setBorder(BorderFactory.createMatteBorder(4,4,4,4,Color.PINK));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        RegisterUser = new javax.swing.JButton();
        ViewUser = new javax.swing.JButton();
        UpdateUser = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        GenerateQr = new javax.swing.JButton();
        ViewQrs = new javax.swing.JButton();
        MarkAttendance = new javax.swing.JButton();
        ViewAttendance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RegisterUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterUser.setText("Register User");
        RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUserActionPerformed(evt);
            }
        });

        ViewUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewUser.setText("View User");
        ViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUserActionPerformed(evt);
            }
        });

        UpdateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateUser.setText("Update User ");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        DeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteUser.setText("Delete User");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        GenerateQr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenerateQr.setText("Generate Qr");
        GenerateQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateQrActionPerformed(evt);
            }
        });

        ViewQrs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewQrs.setText("View Qrs");
        ViewQrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewQrsActionPerformed(evt);
            }
        });

        MarkAttendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MarkAttendance.setText("Mark Attendance");

        ViewAttendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewAttendance.setText("View Attendance");
        ViewAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAttendanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(UpdateUser)
                .addGap(38, 38, 38)
                .addComponent(DeleteUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(GenerateQr, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(ViewQrs, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(MarkAttendance)
                .addGap(28, 28, 28)
                .addComponent(ViewAttendance)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewUser)
                            .addComponent(RegisterUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewAttendance)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MarkAttendance)
                            .addComponent(ViewQrs)
                            .addComponent(GenerateQr)
                            .addComponent(DeleteUser)
                            .addComponent(UpdateUser))))
                .addContainerGap(729, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUserActionPerformed
        // TODO add your handling code here:
        BDUtility.openForm(UserRegistration.class.getSimpleName(), new UserRegistration());
    }//GEN-LAST:event_RegisterUserActionPerformed

    private void ViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUserActionPerformed
        // TODO add your handling code here:
        BDUtility.openForm(ViewUser.class.getSimpleName(), new ViewUser());
    }//GEN-LAST:event_ViewUserActionPerformed

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        // show the delete user page.
        BDUtility.openForm(DeleteUser.class.getSimpleName(), new DeleteUser());
    }//GEN-LAST:event_DeleteUserActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        BDUtility.openForm(UpdateUser.class.getSimpleName(), new UpdateUser());
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void GenerateQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateQrActionPerformed
        // TODO add your handling code here:
                BDUtility.openForm(GenerateAndSaveQr.class.getSimpleName(), new GenerateAndSaveQr());

    }//GEN-LAST:event_GenerateQrActionPerformed

    private void ViewQrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewQrsActionPerformed
        // TODO add your handling code here:
                       BDUtility.openForm(GenerateAndViewQr .class.getSimpleName(), new GenerateAndViewQr ());

    }//GEN-LAST:event_ViewQrsActionPerformed

    private void ViewAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAttendanceActionPerformed
           BDUtility.openForm(ViewAttendance .class.getSimpleName(), new ViewAttendance ());

    }//GEN-LAST:event_ViewAttendanceActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton GenerateQr;
    private javax.swing.JButton MarkAttendance;
    private javax.swing.JButton RegisterUser;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JButton ViewAttendance;
    private javax.swing.JButton ViewQrs;
    private javax.swing.JButton ViewUser;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
